export const LOGGED_IN = 'LOGGED_IN';
export const CHANGE_LIST_BACKGROUND_COLOR = 'CHANGE_LIST_BACKGROUND_COLOR'
export const LOCAL_LOGGED_IN = 'LOCAL_LOGGED_IN'


//AUTH
export const SUBMIT_USER_CREDENTIAL = 'SUBMIT_USER_CREDENTIAL'



//bitcoin
export const FETCH_BITCOIN = 'FETCH_BITCOIN'
export const FETCH_LITECOIN = 'FETCH_LITECOIN'
