export const LOGGED_IN = 'LOGGED_IN';
export const CHANGE_LIST_BACKGROUND_COLOR = 'CHANGE_LIST_BACKGROUND_COLOR'
export const LOCAL_LOGGED_IN = 'LOCAL_LOGGED_IN'


//AUTH
export const SUBMIT_USER_CREDENTIAL = 'SUBMIT_USER_CREDENTIAL'



//bitcoin
export const FETCH_BITCOIN = 'FETCH_BITCOIN'
export const FETCH_LITECOIN = 'FETCH_LITECOIN'


//POST JOB
export const FETCH_ACTION = 'FETCH_ACTION'
export const FUFILLED_ACTION = 'FUFILLED_ACTION'


//FIND JOB
export const FIND_JOB = 'FIND_JOB'
export const FUFILLED_FIND_JOB = 'FUFILLED_FIND_JOB'
export const ERROR_FIND_JOB = 'ERROR_FIND_JOB'
export const DONE_JOB = 'DONE_JOB'

//JOB DETAIL
export const FETCH_JOB_DETAIL = 'FETCH_JOB_DETAIL'
